name = "gbr_disk_log"
version = "1.2.1"
gleam = ">= 1.18.0"
description = "GBR: Gleam wrapper Erlang disk_log"
repository = { type = "github", user = "gleam-br", repo = "gbr_disk_log" }
licences = ["Apache-2.0"]
target = "erlang"

[dependencies]
gleam_stdlib = "~> 1.0"
gleam_erlang = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 1.10"
simplifile = "~> 2.3"
